# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maba.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pymysql


class Ui_Dialog1(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 598)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 801, 101))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(0, 255, 127);")
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 100, 801, 501))
        self.frame.setStyleSheet("background-color: rgb(146, 245, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(240, 380, 75, 23))
        self.pushButton_3.setAutoFillBackground(False)
        self.pushButton_3.setStyleSheet("background-color: rgb(170, 170, 0);")
        self.pushButton_3.clicked.connect(self.Clear)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(560, 380, 75, 23))
        self.pushButton_2.setAutoFillBackground(False)
        self.pushButton_2.setStyleSheet("background-color: rgb(170, 170, 0);")
        self.pushButton_2.clicked.connect(self.Save)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(400, 380, 75, 23))
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("background-color: rgb(170, 170, 0);")
        self.pushButton.clicked.connect(self.Delete)
        self.pushButton.setObjectName("pushButton")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(130, 190, 71, 21))
        self.label_5.setObjectName("label_5")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.frame)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(230, 140, 401, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.plainTextEdit_3.setFont(font)
        self.plainTextEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(self.frame)
        self.plainTextEdit_4.setGeometry(QtCore.QRect(230, 190, 401, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.plainTextEdit_4.setFont(font)
        self.plainTextEdit_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.plainTextEdit_5 = QtWidgets.QPlainTextEdit(self.frame)
        self.plainTextEdit_5.setGeometry(QtCore.QRect(230, 240, 401, 111))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.plainTextEdit_5.setFont(font)
        self.plainTextEdit_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.plainTextEdit_5.setObjectName("plainTextEdit_5")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.frame)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(230, 90, 401, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.plainTextEdit_2.setFont(font)
        self.plainTextEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.frame)
        self.plainTextEdit.setGeometry(QtCore.QRect(230, 40, 401, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(130, 140, 71, 21))
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(130, 240, 71, 21))
        self.label_6.setObjectName("label_6")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(130, 40, 71, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(130, 90, 71, 21))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "D'MABA"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">DATA MAHASISWA BARU </span></p></body></html>"))
        self.pushButton_3.setText(_translate("Dialog", "CLEAR"))
        self.pushButton_2.setText(_translate("Dialog", "SAVE"))
        self.pushButton.setText(_translate("Dialog", "DELETE"))
        self.label_5.setText(_translate("Dialog", "EMAIL"))
        self.label_4.setText(_translate("Dialog", "PHONE"))
        self.label_6.setText(_translate("Dialog", "ADDRESS"))
        self.label_2.setText(_translate("Dialog", "FIRST NAME"))
        self.label_3.setText(_translate("Dialog", "LAST NAME"))

    def Save(self):
        FIRSTNAME = self.plainTextEdit.toPlainText()
        LASTNAME = self.plainTextEdit_2.toPlainText()
        PHONE = self.plainTextEdit_3.toPlainText()
        EMAIL = self.plainTextEdit_4.toPlainText()
        ADDRESS = self.plainTextEdit_5.toPlainText()

        insert = (FIRSTNAME, LASTNAME, PHONE, EMAIL, ADDRESS)
        print(insert)

        con = pymysql.connect(host='localhost', user='root', passwd='', db='dbmaba', port=3306, autocommit=True)
        cur = con.cursor()
        sql = "INSERT INTO maba(First_Name, Last_Name, Phone, Email, Address)"+ \
            "VALUES" +str(insert)
        data = cur.execute(sql)
        if(data):
            self.messagebox("Successful", "Your Data Has Been Saved")
        else:
            self.messagebox("Error", "Your Data Is Not Saved")

    def Delete(self):
        FIRSTNAME = self.plainTextEdit.toPlainText()
        con = pymysql.connect(host='localhost', user='root', passwd='', db='dbmaba', port=3306, autocommit=True)
        cur = con.cursor()
        sql = "DELETE FROM maba where First_Name=%s"
        data = cur.execute(sql, (FIRSTNAME))
        if(data):
            self.messagebox("Successful", "Your Data Has Been Deleted")
        else:
            self.messagebox("Error", "Data Is Not Deleted")
    def Clear(self):
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit_2.setPlainText("")
        self.plainTextEdit_3.setPlainText("")
        self.plainTextEdit_4.setPlainText("")
        self.plainTextEdit_5.setPlainText("")

    def messagebox(self, title, message):
        mess = QtWidgets.QMessageBox()
        mess.setWindowTitle(title)
        mess.setText(message)
        mess.setStandardButtons(QtWidgets.QMessageBox.Ok)
        mess.exec_()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog1()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
